### ISSUE TITLE
mixed scala versions on `buildscript.configurations.classpath`

### ISSUE THREAD

**Issue by tnielens** [scoverage/gradle-scoverage#144]
Hello, 

I've switched my app's scala version from 2.11 to 2.12 and experience this issue with the gradle-scoverage plugin: 
```
Caused by: java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
        at scoverage.report.CoverageAggregator$.aggregate(CoverageAggregator.scala:15)
        at scoverage.report.CoverageAggregator.aggregate(CoverageAggregator.scala)
        at org.scoverage.ScoverageReport$_report_closure1.doCall(ScoverageReport.groovy:45)
        at org.scoverage.ScoverageReport$_report_closure1.doCall(ScoverageReport.groovy)
        at org.scoverage.ScoverageRunner.run(ScoverageRunner.groovy:32)
        at org.scoverage.ScoverageRunner$run.call(Unknown Source)
        at org.scoverage.ScoverageReport.report(ScoverageReport.groovy:41)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
```

I have an old in-house gradle plugin on my buildscript classpath still on version 2.11 of scala which I don't plan to migrate yet. 
Could that be that the scoverage plugin puts scala deps on the buildscript classpath as well?

I inspected my builscript classpath with 
```
task printClasspath {
    doLast {
        println project.buildscript.configurations.classpath.asPath
    }
}
```

The two deps that I suspect are clashing are `my-custom-plugin_2.11-1.0.13.jar` and `gradle-scoverage-4.0.1.jar`. The task `compileScoverageScala` ran fine.

Is `reportTestScoverage` running on a forked jvm with a dedicated classpath?

**Comment by tnielens** [comment]
We modified our in-house plugin and aligned scala versions. Closing as low importance/not-a-bug.
