### ISSUE TITLE
scala-major version detection fails when 'scala-library' actual version customized via resolutionStrategy

### ISSUE THREAD

**Issue by maslovalex** [scoverage/gradle-scoverage#97]
For example using `gradle-scoverage` with `gradle-scala-multiversion-plugin` impossible 

_build.gradle_
```gradle
plugins {
    id 'com.adtran.scala-multiversion-plugin' version '1.0.35'
    id 'org.scoverage' version '3.0.0'
}

repositories {
    jcenter()
}
dependencies {
    compile "org.scala-lang:scala-library:%scala-version%"
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.scalatest:scalatest_%%:3.0.5'

    testRuntimeOnly 'org.scala-lang.modules:scala-xml_%%:1.1.1'
}
```
_gradle.properties_
```properties
scalaVersions = 2.12.8, 2.11.12
```
`./gradlew --stacktrace`

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java_lang_String$substring$4.call(Unknown Source)
        at org.scoverage.ScoveragePlugin$_applyProject_closure4.doCall(ScoveragePlugin.groovy:79)
        at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator
        $BuildOperationEmittingClosure$1$1.run(DefaultListenerBuildOperationDecorator.java:181)
```

**Comment by maiflai** [comment]
Sorry about this - please could you try:

```groovy
scoverage.scoverageScalaVersion = project.scalaVersion
```

as a workaround?

Thanks,
Stu

**Comment by maslovalex** [comment]
changing `build.gradle` to 
```groovy
plugins {
    id "com.adtran.scala-multiversion-plugin" version "1.0.35"
    id "org.scoverage" version "3.0.0"
}

repositories {
    jcenter()
}

scoverage.scoverageScalaVersion = project.scalaVersion

dependencies {
    // compile -> implementation
    implementation "org.scala-lang:scala-library:%scala-version%"
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.scalatest:scalatest_%%:3.0.5'

    testRuntimeOnly 'org.scala-lang.modules:scala-xml_%%:1.1.1'
}
```
renders following error 
```
* What went wrong:
A problem occurred configuring root project 'multiscala-scoverage'.
> Could not resolve all files for configuration ':scoverage'.
   > Could not find org.scoverage:scalac-scoverage-plugin_2.12.8:1.3.1.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/scoverage/scalac-scoverage-plugin_2.12.8/1.3.1/scalac-scoverage-plugin_2.12.8-1.3.1.pom
       - https://jcenter.bintray.com/org/scoverage/scalac-scoverage-plugin_2.12.8/1.3.1/scalac-scoverage-plugin_2.12.8-1.3.1.jar
     Required by:
         project :
   > Could not find org.scoverage:scalac-scoverage-runtime_2.12.8:1.3.1.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/scoverage/scalac-scoverage-runtime_2.12.8/1.3.1/scalac-scoverage-runtime_2.12.8-1.3.1.pom
       - https://jcenter.bintray.com/org/scoverage/scalac-scoverage-runtime_2.12.8/1.3.1/scalac-scoverage-runtime_2.12.8-1.3.1.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by maiflai** [comment]
Ah.

Can you try project.scalaSuffix? I expect you will need to strip the underscore first.

**Comment by maslovalex** [comment]
putting `scoverage.scoverageScalaVersion = project.scalaSuffix.substring(1)` in `build.gradle` fixes the build.

**Comment by eyalroth** [comment]
I created a PR to support any resolution strategy. Spring's dependency management was supported earlier by manually checking if it's configured; with this PR, the plugin is not aware of Spring's plugin directly, but indirectly via the resolution strategy.
